routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Models\Destination;
use App\Models\Hotel;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', [AuthController::class, 'login'])->name('login');
Route::get('register', [AuthController::class, 'register'])->name('register');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');
Route::post('attemptLogin', [AuthController::class, 'attemptLogin'])->name('attemptLogin');
Route::post('storeRegister', [AuthController::class, 'storeRegister'])->name('storeRegister');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/kebutuhanmu/sesuaikan', 'OrderController@custom')->name('order.custom');
Route::get('/pesananku/mailtest/{code}', 'OrderController@testMail')->name('order.testMail');
Route::resource('/kebutuhanmu', 'OrderController');
Route::get('/pesananku/gagal', 'OrderController@failed')->name('order.failed');
Route::get('/pesananku/{code}', 'OrderController@finish')->name('order.finish');

//Modal
Route::get('/modal/penginapan/{id}', 'ModalController@penginapan')->name('modal.penginapan');
Route::get('/modal/destination/{id}', 'ModalController@destination')->name('modal.destination');
Route::get('/modal/wisata/{id}', 'ModalController@wisata')->name('modal.wisata');

//Ajax
Route::get('/ajax/getHotelById/{id}', function ($id) {
    return Hotel::find($id);
});

Route::get('/ajax/getDestinationById/{id}', function ($id) {
    return Destination::find($id);
});

resources/views/page/home.blade.php
@extends('layout.default')
@section('styles')
<link href="{{asset('css/pages/wizard/wizard-1.css')}}" rel="stylesheet" type="text/css" />
@endsection
@section('content')
<!--begin::Home-->
<div class="row mt-20 mt-lg-30">
    <div class="col-lg-6">
        <p class="text-center text-md-left"
            style="font-size: 42px; line-height: 63px; font-weight: bold; color: #152C5B;">
            Tempat Mana Yang <br>
            Ingin Kamu Kunjungi Di <br>
            Bromo?
        </p>
        <small class="text-center text-md-left" style="font-weight: 300; font-size: 16px; line-height: 170%;">
            Perjalananmu lebih mudah, aman dan nyaman bersama Bromokan. <br>
            Media pemesanan Jeep dan homestay dalam sekali sentuh <br>
            dan akan menghubungkan kamu dengan <br>
            destinasi wisata yang ingin kamu kunjungi. <br>
        </small>
        <h1 class="text-primary font-weight-bolder mt-10">
            #BROMOKANSAJA
        </h1>
        <div class="mt-10">
            <a href="{{route('kebutuhanmu.index')}}" class="btn btn-lg btn-secondary" style="font-size: 1.38rem">Pesan
                Sekarang</a>
        </div>
    </div>
    <div class="col-lg-6">
        <img src="{{asset('/media/bg/home-1.png')}}" class="d-none d-md-block w-100">
    </div>
</div>
<!--end::Home-->
<!--end::Entry-->
@endsection